### ISSUE TITLE
找不到路径，怎么回事？

### ISSUE THREAD

**Issue by szluohua** [lovetingyuan/fq#4]
(node:700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, mkdir 'C:\undefiend\shadowsocks\undefined\shadowsocks'
(node:700) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by szluohua** [comment]
找到问题解决了

**Comment by lovetingyuan** [comment]
抱歉，不知道原因，用 `babel` 转义了一下，希望能解决

**Comment by jdfq** [comment]
怎么解决的？

**Comment by lovetingyuan** [comment]
不好意思，这个问题已经修复了，( ╯□╰ )，升级到`2.3.0`版本就可以了，谢谢各位
