### ISSUE TITLE
Windows下无法访问github和google

### ISSUE THREAD

**Issue by htw128** [lovetingyuan/fq#5]
目前已知的就是这两个无法访问。但是google旗下的youtube没问题。提示是无法连接到代理服务器。防火墙已经手动添加了ss和node.js的出入站允许规则。是那个验证的问题么？就是那个google的验证服务，c开头那个...

**Comment by lovetingyuan** [comment]
应该是不需要配置就能访问google的，目前github好像是访问不了，还不知道原因 @htw128

**Comment by htw128** [comment]
我目测是google的人机校验服务没有通过导致的

**Comment by lovetingyuan** [comment]
如果无法成功，可以更换其他账号尝试
